language: go

script:
  - make
  - make test

matrix:
  include:
    - go 1.13.x
      os: osx
      env: GO111MODULE=on GOFLAGS=-mod=vendor
    - go 1.13x
      os: linux
      env: GO111MODULE=off GOFLAGS=
